name: Release Generator

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

permissions:
  contents: write      

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: Release
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    - name: Getting Tag
      id: tag_extractor
      run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
  
    - uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
      with:
        name: NeuroMind ${{ steps.tag_extractor.outputs.latest_tag }}
        generateReleaseNotes: true
        tag: ${{ steps.tag_extractor.outputs.latest_tag }}
